### PR TITLE
Add use_cache feature to use IDL save for transferring large arrays

### PR DESCRIPTION
**Pull request by anthonyjsmith**
Incorporates #7 from @Fmajor.

@Fmajor: I don't have IDL running any more, so could you check the test suite works? And let me know if anything doesn't look right any more (I've moved some things around). (NB: I've added some assertions to your tests, just to make sure they actually test something!)

### CODE REVIEW

**Comment by anthonyjsmith** [comment]
I managed to get IDL working, so I've fixed the tests (mostly - still a couple of unrelated failures with Python 3).

**Comment by Fmajor** [comment]
I have several failed test 
```
pIDLy$ python3 pidly.py                                                                                                                                                                                                 2 ↵   10:40:20
pIDLy 0.2.6: running full tests.
IDL { x86_64 darwin unix Mac OS X 7.1 Apr 21 2009      64      64}
pexpect 4.2.1
Showing (Python -> IDL time) / (IDL -> Python time).

test_100_dicts_float32_double_string (__main__.TestPidly) ... Sending 100 commands to IDL: ....................................................................................................done.
2.369s/0.072s  ok
test_20_function_calls (__main__.TestPidly) ... 1.011s  ok
test_20_function_calls_explicit (__main__.TestPidly) ... 0.512s  ok
test_20_function_calls_really_explicit (__main__.TestPidly) ... 0.506s  ok
test_2d_int_array (__main__.TestPidly) ... 0.000s/0.024s  ok
test_3_3_element_dicts (__main__.TestPidly) ... 0.000s/0.052s  ok
test_3_element_dict (__main__.TestPidly) ... 0.000s/0.050s  ok
test_3d_int_array (__main__.TestPidly) ... 0.000s/0.027s  ok
test_3d_list_of_strings (__main__.TestPidly) ... 0.000s/0.022s  ok
test_4d_int_array (__main__.TestPidly) ... 0.001s/0.032s  ok
test_50_doubles (__main__.TestPidly) ... 0.022s/0.028s  ok
test_50_doubles_1e30 (__main__.TestPidly) ... 0.021s/0.028s  ok
test_50_float32 (__main__.TestPidly) ... 0.001s/0.024s  ok
test_50_float32_1e30 (__main__.TestPidly) ... 0.023s/0.026s  ok
test_6d_int_array_tests_max_n_elements_code_area (__main__.TestPidly) ... Sending 22 commands to IDL: ......................done.
0.885s/0.086s  ok
test_8d_int_array (__main__.TestPidly) ... Sending 22 commands to IDL: ......................done.
0.868s/0.083s  ok
test_dict_string_arrays (__main__.TestPidly) ... 0.001s/0.052s  ok
test_ev_list (__main__.TestPidly) ... 12.43s/12.34s  ok
test_ev_list_with_cache (__main__.TestPidly) ... 0.249s/0.033s  ok
test_ev_with_cache (__main__.TestPidly) ... 0.153s/0.009s  ok
test_huge_double (__main__.TestPidly) ... 0.000s/0.031s  ok
test_idl_dead (__main__.TestPidly) ... ERROR
test_inf_nan_array (__main__.TestPidly) ... 0.000s/0.026s  ok
test_infinity (__main__.TestPidly) ... 0.000s/0.022s  ok
test_infinity_neg (__main__.TestPidly) ... 0.000s/0.027s  ok
test_int_array (__main__.TestPidly) ... 0.000s/0.022s  ok
test_list_of_strings (__main__.TestPidly) ... 0.000s/0.027s  ok
test_long_function_call (__main__.TestPidly) ... Sending 13 commands to IDL: .............done.
0.611s  ok
test_long_function_dicts (__main__.TestPidly) ... Sending 100 commands to IDL: ....................................................................................................done.
2.387s  ok
test_long_int_array (__main__.TestPidly) ... 0.000s/0.023s  ok
test_long_integer (__main__.TestPidly) ... 0.000s/0.022s  ok
test_longest_line (__main__.TestPidly) ... 0.001s/0.055s  ok
test_longest_string (__main__.TestPidly) ... 0.022s/0.052s  ok
test_longest_string_overflow (__main__.TestPidly) ... ok
test_longish_function_call (__main__.TestPidly) ... 0.079s  ok
test_mixed_array_warning (__main__.TestPidly) ... (!) Conversion to numpy.array has changed input from:
[22, 23.0, '24']
to:
['22', '23.0', '24']
0.000s/0.022s  FAIL
test_multi_word_string (__main__.TestPidly) ... 0.000s/0.026s  ok
test_nan (__main__.TestPidly) ... 0.000s/0.025s  ok
test_simple_dictionary (__main__.TestPidly) ... 0.000s/0.056s  ok
test_single_element_list_int (__main__.TestPidly) ... 0.000s/0.025s  ok
test_single_float (__main__.TestPidly) ... 0.000s/0.024s  ok
test_single_float32 (__main__.TestPidly) ... 0.000s/0.026s  ok
test_single_integer (__main__.TestPidly) ... 0.000s/0.022s  ok
test_single_string (__main__.TestPidly) ... 0.000s/0.025s  ok
test_speed_20000_doubles (__main__.TestPidly) ... Sending 237 commands to IDL: .............................................................................................................................................................................................................................................done.
11.34s/0.479s  ok
test_speed_5000_doubles_one_by_one (__main__.TestPidly) ... 100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500 2600 2700 2800 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100 4200 4300 4400 4500 4600 4700 4800 4900 5000 2.161s/0.161s  ok
pidly ()
Doctest: pidly ... ok
IDL (pidly)
Doctest: pidly.IDL ... FAIL

======================================================================
ERROR: test_idl_dead (__main__.TestPidly)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pidly.py", line 1052, in test_idl_dead
    self.idl('exit')
  File "pidly.py", line 290, in ex
    idl_output = self._wait_for_prompt(print_output=print_output)
  File "pidly.py", line 827, in _wait_for_prompt
    index = self.expect([self.idl_prompt, '\n', pexpect.EOF])
  File "/Users/fmajor/Library/Python/3.6/lib/python/site-packages/pexpect-4.2.1-py3.6.egg/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/Users/fmajor/Library/Python/3.6/lib/python/site-packages/pexpect-4.2.1-py3.6.egg/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/Users/fmajor/Library/Python/3.6/lib/python/site-packages/pexpect-4.2.1-py3.6.egg/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/Users/fmajor/Library/Python/3.6/lib/python/site-packages/pexpect-4.2.1-py3.6.egg/pexpect/pty_spawn.py", line 465, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/Users/fmajor/Library/Python/3.6/lib/python/site-packages/pexpect-4.2.1-py3.6.egg/pexpect/spawnbase.py", line 159, in read_nonblocking
    self.flag_eof = True
  File "pidly.py", line 443, in __setattr__
    self.ex(name, value)
  File "pidly.py", line 287, in ex
    if self._send_expression_to_idl(expression):  # Any bytes sent?
  File "pidly.py", line 474, in _send_expression_to_idl
    raise OSError("IDL session is not alive.")
OSError: IDL session is not alive.

======================================================================
FAIL: test_mixed_array_warning (__main__.TestPidly)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pidly.py", line 1281, in test_mixed_array_warning
    y.dtype.name[0:6])
AssertionError: 'str102' != 'str128'
- str102
?     -
+ str128
?      +


======================================================================
FAIL: IDL (pidly)
Doctest: pidly.IDL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 2199, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pidly.IDL
  File "/Users/fmajor/sourceCode/github/pIDLy/pidly.py", line 91, in IDL

----------------------------------------------------------------------
File "/Users/fmajor/sourceCode/github/pIDLy/pidly.py", line 129, in pidly.IDL
Failed example:
    print(list(xy.keys()))
Expected:
    ['y', 'x']
Got:
    ['x', 'y']


----------------------------------------------------------------------
Ran 48 tests in 59.291s

FAILED (failures=2, errors=1)
```

the failed of doctest can be solved by `print(sorted(list(xy.keys())))`

**Comment by anthonyjsmith** [comment]
Tests should be fixed now. OK to proceed from your perspective?

**Comment by Fmajor** [comment]
All test pass. 🙂

**Pull request merged**
